remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache
title: Randriksen - Certifialble?
description: Things that I find interesting, annoying or both.

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-46KFSDJ0Y1"
    anonymize_ip: false # default


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/randriksen
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/ole-rand-hendriksen/
    